### ISSUE TITLE
correct the pounciation for 看板 kan ban and explain the structure of tones and characters in Chinese

### ISSUE THREAD

**Issue by flicksolutions** [flicksolutions/cdh-github-example#1]

**Comment by dimpurr** [comment]
Issues is helpful while seeking help, asking why the code is not working, and tracking the process of updating the codes based on feedback.

**Comment by 0066cc** [comment]
👋

**Comment by dimpurr** [comment]
Realted commits: https://github.com/flicksolutions/cdh-github-example/commit/259b24bf5826b4700607318d93c7d30cf79ae3e4
